/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedCryptoRouteImport } from './routes/_authenticated/crypto'
import { Route as AuthenticatedIncomeExpensesRouteImport } from './routes/_authenticated/income-expenses'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedRulesRouteImport } from './routes/_authenticated/rules'
import { Route as AuthenticatedSpendingRouteImport } from './routes/_authenticated/spending'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAccountsRouteImport } from './routes/demo/accounts'
import { Route as DemoCryptoRouteImport } from './routes/demo/crypto'
import { Route as DemoIncomeExpensesRouteImport } from './routes/demo/income-expenses'
import { Route as DemoPortfolioRouteImport } from './routes/demo/portfolio'
import { Route as DemoRulesRouteImport } from './routes/demo/rules'
import { Route as DemoSpendingRouteImport } from './routes/demo/spending'
import { Route as DemoSubscriptionsRouteImport } from './routes/demo/subscriptions'
import { Route as DemoTransactionsRouteImport } from './routes/demo/transactions'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCryptoRoute = AuthenticatedCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomeExpensesRoute =
  AuthenticatedIncomeExpensesRouteImport.update({
    id: '/income-expenses',
    path: '/income-expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRulesRoute = AuthenticatedRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpendingRoute = AuthenticatedSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoAccountsRoute = DemoAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoCryptoRoute = DemoCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoIncomeExpensesRoute = DemoIncomeExpensesRouteImport.update({
  id: '/income-expenses',
  path: '/income-expenses',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoPortfolioRoute = DemoPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoRulesRoute = DemoRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSpendingRoute = DemoSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSubscriptionsRoute = DemoSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTransactionsRoute = DemoTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/income-expenses': typeof AuthenticatedIncomeExpensesRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/crypto': typeof DemoCryptoRoute
  '/demo/income-expenses': typeof DemoIncomeExpensesRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/rules': typeof DemoRulesRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/demo/subscriptions': typeof DemoSubscriptionsRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/income-expenses': typeof AuthenticatedIncomeExpensesRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/rules': typeof AuthenticatedRulesRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/crypto': typeof DemoCryptoRoute
  '/demo/income-expenses': typeof DemoIncomeExpensesRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/rules': typeof DemoRulesRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/demo/subscriptions': typeof DemoSubscriptionsRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/crypto': typeof AuthenticatedCryptoRoute
  '/_authenticated/income-expenses': typeof AuthenticatedIncomeExpensesRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/rules': typeof AuthenticatedRulesRoute
  '/_authenticated/spending': typeof AuthenticatedSpendingRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/demo/accounts': typeof DemoAccountsRoute
  '/demo/crypto': typeof DemoCryptoRoute
  '/demo/income-expenses': typeof DemoIncomeExpensesRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/rules': typeof DemoRulesRoute
  '/demo/spending': typeof DemoSpendingRoute
  '/demo/subscriptions': typeof DemoSubscriptionsRoute
  '/demo/transactions': typeof DemoTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/auth'
    | '/accounts'
    | '/crypto'
    | '/income-expenses'
    | '/portfolio'
    | '/rules'
    | '/spending'
    | '/subscriptions'
    | '/transactions'
    | '/demo/accounts'
    | '/demo/crypto'
    | '/demo/income-expenses'
    | '/demo/portfolio'
    | '/demo/rules'
    | '/demo/spending'
    | '/demo/subscriptions'
    | '/demo/transactions'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/accounts'
    | '/crypto'
    | '/income-expenses'
    | '/portfolio'
    | '/rules'
    | '/spending'
    | '/subscriptions'
    | '/transactions'
    | '/demo/accounts'
    | '/demo/crypto'
    | '/demo/income-expenses'
    | '/demo/portfolio'
    | '/demo/rules'
    | '/demo/spending'
    | '/demo/subscriptions'
    | '/demo/transactions'
    | '/'
    | '/demo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/demo'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/crypto'
    | '/_authenticated/income-expenses'
    | '/_authenticated/portfolio'
    | '/_authenticated/rules'
    | '/_authenticated/spending'
    | '/_authenticated/subscriptions'
    | '/_authenticated/transactions'
    | '/demo/accounts'
    | '/demo/crypto'
    | '/demo/income-expenses'
    | '/demo/portfolio'
    | '/demo/rules'
    | '/demo/spending'
    | '/demo/subscriptions'
    | '/demo/transactions'
    | '/_authenticated/'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto': {
      id: '/_authenticated/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof AuthenticatedCryptoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/income-expenses': {
      id: '/_authenticated/income-expenses'
      path: '/income-expenses'
      fullPath: '/income-expenses'
      preLoaderRoute: typeof AuthenticatedIncomeExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rules': {
      id: '/_authenticated/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AuthenticatedRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spending': {
      id: '/_authenticated/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AuthenticatedSpendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/accounts': {
      id: '/demo/accounts'
      path: '/accounts'
      fullPath: '/demo/accounts'
      preLoaderRoute: typeof DemoAccountsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/crypto': {
      id: '/demo/crypto'
      path: '/crypto'
      fullPath: '/demo/crypto'
      preLoaderRoute: typeof DemoCryptoRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/income-expenses': {
      id: '/demo/income-expenses'
      path: '/income-expenses'
      fullPath: '/demo/income-expenses'
      preLoaderRoute: typeof DemoIncomeExpensesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/portfolio': {
      id: '/demo/portfolio'
      path: '/portfolio'
      fullPath: '/demo/portfolio'
      preLoaderRoute: typeof DemoPortfolioRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/rules': {
      id: '/demo/rules'
      path: '/rules'
      fullPath: '/demo/rules'
      preLoaderRoute: typeof DemoRulesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/spending': {
      id: '/demo/spending'
      path: '/spending'
      fullPath: '/demo/spending'
      preLoaderRoute: typeof DemoSpendingRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/subscriptions': {
      id: '/demo/subscriptions'
      path: '/subscriptions'
      fullPath: '/demo/subscriptions'
      preLoaderRoute: typeof DemoSubscriptionsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/transactions': {
      id: '/demo/transactions'
      path: '/transactions'
      fullPath: '/demo/transactions'
      preLoaderRoute: typeof DemoTransactionsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedCryptoRoute: typeof AuthenticatedCryptoRoute
  AuthenticatedIncomeExpensesRoute: typeof AuthenticatedIncomeExpensesRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedRulesRoute: typeof AuthenticatedRulesRoute
  AuthenticatedSpendingRoute: typeof AuthenticatedSpendingRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedCryptoRoute: AuthenticatedCryptoRoute,
  AuthenticatedIncomeExpensesRoute: AuthenticatedIncomeExpensesRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedRulesRoute: AuthenticatedRulesRoute,
  AuthenticatedSpendingRoute: AuthenticatedSpendingRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoRouteRouteChildren {
  DemoAccountsRoute: typeof DemoAccountsRoute
  DemoCryptoRoute: typeof DemoCryptoRoute
  DemoIncomeExpensesRoute: typeof DemoIncomeExpensesRoute
  DemoPortfolioRoute: typeof DemoPortfolioRoute
  DemoRulesRoute: typeof DemoRulesRoute
  DemoSpendingRoute: typeof DemoSpendingRoute
  DemoSubscriptionsRoute: typeof DemoSubscriptionsRoute
  DemoTransactionsRoute: typeof DemoTransactionsRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoAccountsRoute: DemoAccountsRoute,
  DemoCryptoRoute: DemoCryptoRoute,
  DemoIncomeExpensesRoute: DemoIncomeExpensesRoute,
  DemoPortfolioRoute: DemoPortfolioRoute,
  DemoRulesRoute: DemoRulesRoute,
  DemoSpendingRoute: DemoSpendingRoute,
  DemoSubscriptionsRoute: DemoSubscriptionsRoute,
  DemoTransactionsRoute: DemoTransactionsRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
