// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diwezyrtlwdbrsgegkay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpd2V6eXJ0bHdkYnJzZ2Vna2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyOTkxMzMsImV4cCI6MjEwMzg3NTEzM30.V7u9AVIktvZalM3VcYVcT26LSp1pqOiob6jIgB8Q0n0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});