// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"];
const SUPABASE_PUBLISHABLE_KEY = import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY — see .env.example",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

// A second client with no session persistence, always talking as the
// anonymous role, regardless of what's logged in elsewhere in this browser.
// Used by /demo so the public demo never depends on (or leaks) a real session.
export const demoSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  }
});

export const isDemoRoute = () =>
  typeof window !== "undefined" && window.location.pathname.startsWith("/demo");

// Compatibility accessor used across the app — routes to the read-only anon
// client on /demo, real client everywhere else, so every page's existing
// data-fetching code works unchanged in both places.
export const getSupabase = () => (isDemoRoute() ? demoSupabase : supabase);
